name: build

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Docker
        run: |
          docker build --tag hosts:hostz .
          docker run -v "/var/run/docker.sock":"/var/run/docker.sock" --name hosts-hostz --entrypoint=/hosts/entrypoint.sh hosts:hostz
          docker cp hosts-hostz:hosts/build/hosts ./build/hosts
          
      - name: commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit --allow-empty -m "$(git log -1 --pretty=%s)"
          git push
          
